stages:
    load_data:
        cmd: python src\load_data.py --config=params.yaml
        deps:
        - src\get_data.py
        - src\load_data.py
        - data_given\creditcard.csv
        outs:
        - data\raw\creditcard.csv
    split_data:
        cmd: python src\split_data.py --config=params.yaml
        deps:
        - src\split_data.py
        - data\raw\creditcard.csv
        outs:
        - data\processed\train_creditcard.csv
        - data\processed\test_creditcard.csv 