base:
    project: fraud detection
    random_state: 42
    target_col: Class

data_source:
    s3_source: data_given/creditcard.csv
    
load_data:
    raw_dataset_csv: data/raw/creditcard.csv
    
split_data:
    train_path: data/processed/train_creditcard.csv
    test_path: data/processed/test_creditcard.csv
    test_size:0.2


model_dir: saved_models